version: "3.8"

services:
  yt-podcasts:
    image: ghcr.io/jigaowan/yt-podcasts:master
    container_name: yt-podcasts
    restart: unless-stopped
    volumes:
      - ./downloads:/downloads
      - ./list.txt:/app/list.txt:ro
      - ./logs:/var/log # Optional log mapping
    environment:
      # Set container timezone
      - TZ=Asia/Singapore
      # Define the cron schedule (e.g., every hour at minute 0)
      - CRON_SCHEDULE=37 4 * * *
